# Generated by Django 2.1.1 on 2020-06-24 15:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTasks',
            fields=[
                ('execute_id', models.AutoField(help_text='执行编号', primary_key=True, serialize=False, verbose_name='执行编号')),
                ('state', models.CharField(choices=[('0', '已完成'), ('1', '待审核'), ('2', '已驳回')], default='1', help_text='状态', max_length=10, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('complete_user', models.ForeignKey(help_text='完成人', max_length=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complete_task', to=settings.AUTH_USER_MODEL, verbose_name='完成人')),
            ],
            options={
                'verbose_name': '任务完成信息',
                'verbose_name_plural': '任务完成信息',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tasks_id', models.AutoField(help_text='任务编号', primary_key=True, serialize=False, verbose_name='任务编号')),
                ('url', models.CharField(help_text='会员等级名称', max_length=200, verbose_name='视频链接')),
                ('target_times', models.IntegerField(help_text='目标次数', verbose_name='目标次数')),
                ('completed_times', models.IntegerField(help_text='已完成次数', verbose_name='已完成次数')),
                ('requirement', models.CharField(choices=[('1', '点赞'), ('2', '关注'), ('3', '点赞加关注')], help_text='任务要求', max_length=10, verbose_name='任务要求')),
                ('total_cost', models.CharField(help_text='费用总计', max_length=11, verbose_name='费用总计')),
                ('state', models.CharField(choices=[('0', '未支付'), ('1', '已支付'), ('2', '已完成')], default='0', help_text='状态', max_length=10, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('created', models.ForeignKey(help_text='创建人', max_length=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_task', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务信息',
            },
        ),
        migrations.AddField(
            model_name='completetasks',
            name='tasks_id',
            field=models.ForeignKey(help_text='任务编号', max_length=11, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Tasks', verbose_name='任务编号'),
        ),
    ]
