# Generated by Django 2.1.1 on 2020-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetasks',
            name='remarks',
            field=models.CharField(blank=True, help_text='备注', max_length=360, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='completetasks',
            name='state',
            field=models.CharField(choices=[('0', '已完成'), ('1', '待审核'), ('2', '已驳回')], default='1', help_text='状态 0：已完成,1：待审核,2:已驳回', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='requirement',
            field=models.CharField(choices=[('1', '点赞'), ('2', '关注'), ('3', '点赞加关注')], help_text='任务要求  1:点赞,2:关注,3:点赞加关注', max_length=10, verbose_name='任务要求'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='state',
            field=models.CharField(choices=[('0', '未支付'), ('1', '已支付'), ('2', '已完成')], default='0', help_text='状态  0:未支付,1:已支付,2:已完成', max_length=10, verbose_name='状态'),
        ),
    ]
