# Generated by Django 2.1.1 on 2020-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200624_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='requirement',
            field=models.CharField(choices=[('1', '点赞'), ('2', '点赞加关注'), ('3', '点赞加关注加评论')], help_text='任务要求  1:点赞,2:关注,3:点赞加关注', max_length=10, verbose_name='任务要求'),
        ),
    ]
