# Generated by Django 2.1.1 on 2020-06-26 10:05

import apps.tasks.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200626_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(storage=apps.tasks.storage.ImageStorage(), upload_to='img/%Y%m%d', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='completetasks',
            name='image',
            field=models.ImageField(storage=apps.tasks.storage.ImageStorage(), upload_to='img/%Y%m%d', verbose_name='任务图片'),
        ),
    ]
