# Generated by Django 2.1.1 on 2020-06-27 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200627_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed_times',
            field=models.IntegerField(default='0', help_text='已完成次数', verbose_name='已完成次数'),
        ),
    ]
