# Generated by Django 2.1.1 on 2020-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200627_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed_times',
            field=models.IntegerField(blank=True, default='0', help_text='已完成次数', null=True, verbose_name='已完成次数'),
        ),
    ]
