# Generated by Django 2.1.1 on 2020-06-27 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20200627_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed_times',
            field=models.IntegerField(blank=True, help_text='已完成次数', null=True, verbose_name='已完成次数'),
        ),
    ]
