# Generated by Django 2.1.1 on 2020-06-27 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20200627_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='requirement',
        ),
        migrations.AddField(
            model_name='tasks',
            name='tasks_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='任务名称', max_length=360, verbose_name='任务名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed_times',
            field=models.IntegerField(blank=True, default='0', help_text='已完成次数', null=True, verbose_name='已完成次数'),
        ),
    ]
