# Generated by Django 2.1.1 on 2020-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20200627_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='cost',
            field=models.CharField(default=1, help_text='单条价格', max_length=11, verbose_name='单条价格'),
            preserve_default=False,
        ),
    ]
