# Generated by Django 2.1.1 on 2020-06-27 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tasks_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.ForeignKey(help_text='创建人', max_length=11, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_task', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
