# Generated by Django 2.1.1 on 2020-06-28 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20200627_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completetasks',
            name='complete_user',
            field=models.ForeignKey(help_text='完成人', max_length=11, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complete_task', to=settings.AUTH_USER_MODEL, verbose_name='完成人'),
        ),
    ]
