# Generated by Django 2.1.1 on 2020-07-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20200629_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='complete_cost',
            field=models.CharField(default=1, help_text='单条完成价格', max_length=11, verbose_name='单条完成价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='state',
            field=models.CharField(choices=[('0', '未支付'), ('1', '已支付'), ('2', '审核通过'), ('3', '审核不通过'), ('4', '已完成')], default='0', help_text='状态  0:未支付,1:已支付,2:已完成', max_length=10, verbose_name='状态'),
        ),
    ]
