# Generated by Django 2.1.1 on 2020-07-02 00:27

import apps.tasks.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20200701_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(storage=apps.tasks.storage.ImageStorage(), upload_to='img/%Y/%m/%d', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图片信息表',
                'verbose_name_plural': '图片信息表',
            },
        ),
        migrations.RemoveField(
            model_name='completetasks',
            name='image',
        ),
        migrations.AddField(
            model_name='completetasks',
            name='image',
            field=models.ManyToManyField(blank=True, help_text='照片', to='tasks.ImageInfo', verbose_name='照片'),
        ),
    ]
