# Generated by Django 2.1.1 on 2020-07-02 21:11

import apps.tasks.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20200702_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(help_text='图片id', primary_key=True, serialize=False, verbose_name='图片id')),
                ('url', models.ImageField(storage=apps.tasks.storage.ImageStorage(), upload_to='img/%Y/%m/%d', verbose_name='图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图片信息表',
                'verbose_name_plural': '图片信息表',
            },
        ),
        migrations.RemoveField(
            model_name='completetasks',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='completetasks',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='completetasks',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='completetasks',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='completetasks',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='completetasks',
            name='image6',
        ),
        migrations.AddField(
            model_name='completetasks',
            name='image',
            field=models.ManyToManyField(blank=True, help_text='照片', to='tasks.ImageInfo', verbose_name='照片'),
        ),
    ]
