# Generated by Django 2.1.1 on 2020-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20200702_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completetasks',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='价格', max_digits=9, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='complete_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='单条完成价格', max_digits=9, verbose_name='单条完成价格'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='发布任务价格', max_digits=9, verbose_name='发布任务价格'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='费用总计', max_digits=9, verbose_name='费用总计'),
        ),
        migrations.AlterField(
            model_name='taskstype',
            name='complete_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='完成任务价格', max_digits=9, verbose_name='完成任务价格'),
        ),
        migrations.AlterField(
            model_name='taskstype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='发布任务价格', max_digits=9, verbose_name='发布任务价格'),
        ),
    ]
