# Generated by Django 2.1.1 on 2020-07-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20200704_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasksType',
        ),
    ]
