# Generated by Django 2.1.1 on 2020-07-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0029_auto_20200705_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='created',
            field=models.ForeignKey(help_text='创建人', max_length=11, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='member',
            field=models.BooleanField(default=False, help_text='是否开通会员转账', verbose_name='是否开通会员转账'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='state',
            field=models.CharField(choices=[('0', '已支付'), ('1', '已退回'), ('2', '驳回，已退款')], default='0', help_text='状态 0：已支付, 1：审核通过, 2：驳回，已退款', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='tasks_id',
            field=models.ForeignKey(blank=True, help_text='任务编号或者会员编号', max_length=11, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Tasks', verbose_name='任务编号或者会员编号'),
        ),
    ]
