# Generated by Django 2.1.1 on 2020-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20200707_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='tasks_id',
            field=models.CharField(default=39, help_text='任务编号或者会员编号', max_length=200, verbose_name='任务编号或者会员编号'),
            preserve_default=False,
        ),
    ]
