# Generated by Django 2.1.1 on 2020-06-27 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('new_id', models.AutoField(help_text='公告id', primary_key=True, serialize=False, verbose_name='公告id')),
                ('new_title', models.CharField(help_text='公告标题', max_length=11, verbose_name='公告标题')),
                ('new_content', models.CharField(help_text='公告内容', max_length=11, verbose_name='公告内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻公告',
                'verbose_name_plural': '新闻公告',
            },
        ),
    ]
