# Generated by Django 2.1.1 on 2020-06-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='new_content',
            field=models.CharField(help_text='公告内容', max_length=6400, verbose_name='公告内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='new_title',
            field=models.CharField(help_text='公告标题', max_length=360, verbose_name='公告标题'),
        ),
    ]
