# Generated by Django 2.1.1 on 2020-06-24 15:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capital_id', models.AutoField(help_text='明细编号', primary_key=True, serialize=False, verbose_name='明细编号')),
                ('type', models.CharField(choices=[('0', '收入'), ('1', '支出')], help_text='类型', max_length=10, verbose_name='类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('execute_id', models.ForeignKey(blank=True, help_text='执行编号', max_length=11, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.CompleteTasks', verbose_name='执行编号')),
                ('tasks_id', models.ForeignKey(blank=True, help_text='任务编号', max_length=11, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Tasks', verbose_name='任务编号')),
                ('user', models.ForeignKey(help_text='所属人', max_length=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='capital_user', to=settings.AUTH_USER_MODEL, verbose_name='所属人')),
            ],
            options={
                'verbose_name': '资金明细',
                'verbose_name_plural': '资金明细',
            },
        ),
        migrations.CreateModel(
            name='MoneyRecord',
            fields=[
                ('record_id', models.AutoField(help_text='记录编号', primary_key=True, serialize=False, verbose_name='记录编号')),
                ('money', models.CharField(help_text='提现金额', max_length=11, verbose_name='提现金额')),
                ('state', models.CharField(choices=[('0', '已放款'), ('1', '待放款'), ('2', '已驳回')], default='1', help_text='状态', max_length=10, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('user', models.ForeignKey(help_text='提现人', max_length=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_record_user', to=settings.AUTH_USER_MODEL, verbose_name='提现人')),
            ],
            options={
                'verbose_name': '提现记录',
                'verbose_name_plural': '提现记录',
            },
        ),
    ]
