# Generated by Django 2.1.1 on 2020-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrecord',
            name='remarks',
            field=models.CharField(blank=True, help_text='备注', max_length=360, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='moneyrecord',
            name='state',
            field=models.CharField(choices=[('0', '已放款'), ('1', '待放款'), ('2', '已驳回')], default='1', help_text='状态  0：已放款,1:待放款,2:已驳回', max_length=10, verbose_name='状态'),
        ),
    ]
