# Generated by Django 2.1.1 on 2020-06-28 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_auto_20200624_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='user',
            field=models.ForeignKey(help_text='所属人', max_length=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='capital_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='所属人'),
        ),
        migrations.AlterField(
            model_name='moneyrecord',
            name='user',
            field=models.ForeignKey(help_text='提现人', max_length=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_record_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='提现人'),
        ),
    ]
