# Generated by Django 2.1.1 on 2020-06-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0004_auto_20200629_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='money',
            field=models.CharField(default=100, help_text='价格', max_length=128, verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capital',
            name='operation',
            field=models.CharField(default=200, help_text='类型', max_length=128, verbose_name='执行操作'),
            preserve_default=False,
        ),
    ]
