# Generated by Django 2.1.1 on 2020-07-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0005_auto_20200629_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='execute_id',
        ),
        migrations.RemoveField(
            model_name='capital',
            name='tasks_id',
        ),
    ]
