# Generated by Django 2.1.1 on 2020-07-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0006_auto_20200704_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='user',
            field=models.CharField(help_text='所属人', max_length=128, verbose_name='所属人'),
        ),
    ]
