# Generated by Django 2.1.1 on 2020-07-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0007_auto_20200704_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='金额', max_digits=9, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='moneyrecord',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='提现金额', max_digits=9, verbose_name='提现金额'),
        ),
    ]
