# Generated by Django 2.1.1 on 2020-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0008_auto_20200704_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrecord',
            name='state',
            field=models.CharField(blank=True, choices=[('0', '待放款'), ('1', '已放款'), ('2', '已驳回')], default='0', help_text='状态  0：待放款,1:已放款,2:已驳回', max_length=10, null=True, verbose_name='状态'),
        ),
    ]
