# Generated by Django 2.1.1 on 2020-07-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0009_auto_20200707_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='提现人', max_length=11, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_record_user', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='提现人'),
        ),
    ]
