# Generated by Django 2.1.1 on 2020-06-24 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(help_text='会员编号', primary_key=True, serialize=False, verbose_name='会员编号')),
                ('member_name', models.CharField(help_text='会员等级名称', max_length=10, verbose_name='会员等级名称')),
                ('common_num', models.CharField(help_text='普通任务条数', max_length=10, verbose_name='普通任务条数')),
                ('member_num', models.CharField(help_text='会员任务条数', max_length=10, verbose_name='会员任务条数')),
                ('time', models.CharField(help_text='有效期限', max_length=11, verbose_name='有效期限')),
                ('place', models.CharField(help_text='价格', max_length=11, verbose_name='价格')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '会员信息',
                'verbose_name_plural': '会员信息',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='task_num',
            field=models.CharField(blank=True, help_text='普通任务条数', max_length=10, null=True, verbose_name='普通任务条数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_level',
            field=models.ForeignKey(blank=True, help_text='会员等级', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Member', verbose_name='会员等级'),
        ),
    ]
