# Generated by Django 2.1.1 on 2020-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200624_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(choices=[('0', '无会员'), ('1', '青铜'), ('2', '白银'), ('3', '黄金'), ('4', '白金'), ('5', '钻石')], help_text='会员等级名称', max_length=10, verbose_name='会员等级名称'),
        ),
    ]
