# Generated by Django 2.1.1 on 2020-06-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200625_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ZFB_account',
            field=models.CharField(blank=True, help_text='支付宝账号', max_length=30, null=True, verbose_name='支付宝账号'),
        ),
    ]
