# Generated by Django 2.1.1 on 2020-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200625_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member_limit',
            field=models.CharField(blank=True, help_text='会员到期日 格式：2020-06-30', max_length=10, null=True, verbose_name='会员到期日'),
        ),
    ]
