# Generated by Django 2.1.1 on 2020-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_member_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='time',
            field=models.CharField(help_text='有效期限：单位：年', max_length=11, verbose_name='有效期限'),
        ),
    ]
