# Generated by Django 2.1.1 on 2020-06-28 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200625_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invitation_name',
            field=models.ForeignKey(blank=True, help_text='邀请人', max_length=30, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='邀请人'),
        ),
    ]
