# Generated by Django 2.1.1 on 2020-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200628_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='余额', max_digits=16, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='套餐提成', max_digits=9, verbose_name='套餐提成'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='task_reward',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='任务奖励', max_digits=9, verbose_name='任务奖励'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='团队收益', max_digits=9, verbose_name='团队收益'),
        ),
    ]
