# Generated by Django 2.1.1 on 2020-07-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200704_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='task_num',
        ),
        migrations.AlterField(
            model_name='member',
            name='place',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='价格', max_digits=16, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member_level',
            field=models.ForeignKey(blank=True, default='0', help_text='会员等级', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Member', verbose_name='会员等级'),
        ),
    ]
