# Generated by Django 2.1.1 on 2020-07-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200704_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='time_type',
            field=models.CharField(choices=[('0', '无会员'), ('1', '青铜'), ('2', '白银'), ('3', '黄金'), ('4', '白金'), ('5', '钻石')], default=1, help_text='期限类型 0.日 1.月 2.年', max_length=10, verbose_name='期限类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='time',
            field=models.IntegerField(help_text='有效期限：单位：年', max_length=11, verbose_name='有效期限'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member_limit',
            field=models.CharField(blank=True, help_text='会员到期日 格式：20200630', max_length=10, null=True, verbose_name='会员到期日'),
        ),
    ]
