# Generated by Django 2.1.1 on 2020-07-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200709_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='time_type',
            field=models.CharField(choices=[('0', '日'), ('1', '月'), ('2', '年')], help_text='期限类型 0.日 1.月 2.年', max_length=10, verbose_name='期限类型'),
        ),
    ]
