# Generated by Django 2.1.1 on 2020-07-10 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200709_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(help_text='会员编号', primary_key=True, serialize=False, verbose_name='会员编号')),
                ('tasks_today', models.CharField(max_length=10, verbose_name='今日任务数')),
                ('user_today', models.CharField(max_length=11, verbose_name='今日用户数')),
                ('complete', models.CharField(max_length=11, verbose_name='今日已完成')),
                ('goal', models.CharField(max_length=11, verbose_name='今日排行榜')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'APP首页数据',
                'verbose_name_plural': 'APP首页数据',
            },
        ),
    ]
